# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt update && \
    apt install -y sudo bash iproute2 ca-certificates systemd docker.io \
    python3 python3-pip python3-apt python3-docker && \
    apt clean
