---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:11
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: loki

provisioner:
  name: ansible
verifier:
  name: ansible
  lint:
    name: ansible-lint
