---
galaxy_info:
  role_name: grafana
  author: Ambrosus Team
  description: Grafana
  company: Ambrosus
  license: BSD
  min_ansible_version: "2.8"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
