---
galaxy_info:
  role_name: loki
  author: Ambrosus Team
  description: Loki
  company: Ambrosus
  license: BSD
  min_ansible_version: "2.8"
  platforms:
    - name: Debian
      versions:
        - all
